
language: objective-c
osx_image: xcode9.4.1 
script:
  - xcodebuild -scheme runFastK -workspace runFastK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' build test
after_success:
- bash <(curl -s https://codecov.io/bash) -t 5b6f4cb7-3232-497f-8aba-5785b3e0757e